### ISSUE TITLE
AttributeError: 'CarlaSim' object has no attribute '_CarlaSim__world'

### ISSUE THREAD

**Issue by limeng-1234** [uoe-agents/IGP2#4]
Hello, this is a great research. I'm running the ‘’carla_traffic_manager.py‘’  and it shows the error  'CarlaSim' object has no attribute '_CarlaSim__world'.  However I did not find attribute '_CarlaSim__world' in this project. I am looking forward to your answer!

**Comment by gyevnarb** [comment]
Hi!
Thanks for your comment. You are most likely running the code from the wrong directory. Can you try running the script from the root folder of IGP2 and see if that works?
