### ISSUE TITLE
Missing agent.set_destination 

### ISSUE THREAD

**Issue by chenghuang66** [uoe-agents/IGP2#5]
When i reproduce the section 'running simulations in CARLA',  I find that the function set_destination() in igp2/igp2/agents/traffic_agent.py could not match the TrafficManager class in __find_destination(self, agent: ip.TrafficAgent), and i get the following error.  Do I make some mistakes？
> > Traceback (most recent call last):
>   File "carla_traffic_manager.py", line 136, in <module>
>     main()
>   File "carla_traffic_manager.py", line 126, in main
>     tm.update(simulation)
>   File "/home/cwh/mid2mid/aigp2/igp2/carla/traffic_manager.py", line 74, in update
>     self.__spawn_agent(simulation)
>   File "/home/cwh/mid2mid/aigp2/igp2/carla/traffic_manager.py", line 124, in __spawn_agent
>     self.__find_destination(agent)
>   File "/home/cwh/mid2mid/aigp2/igp2/carla/traffic_manager.py", line 136, in __find_destination
>     agent.set_destination(goal, self.__scenario_map)
>   File "/home/cwh/mid2mid/aigp2/igp2/agents/traffic_agent.py", line 35, in set_destination
>     observation.frame,
> AttributeError: 'PointGoal' object has no attribute 'frame

**Comment by gyevnarb** [comment]
Hi sorry for the late reply. We have recently pushed an update to the main branch which should hopefully have resolved your issue.
