### ISSUE TITLE
no ip.carla.TrafficAgent in scripts/carla_mcts_scenario.py file

### ISSUE THREAD

**Issue by AmyGanLU** [uoe-agents/IGP2#6]
Hi,
I am trying to run igp2 in carla. There is an error when running carla_mcts_scenario.py showing that no ip.carla.TrafficAgent. This class does not exist. When i changed it to ip.TrafficAgent, the member function set_destination also came to an error showing "PointGoal" object has no atrribute frame. I guess the example maybe does not consist with the igp2 code.

**Comment by gyevnarb** [comment]
Hi, the code on the main branch was slightly out of date. We have pushed a recent update to the main branch which should have hopefully resolved your issue.
